spring.application.name=equipo-cliente

spring.datasource.url=${DB_URL:jdbc:mysql://mysql-32865d12-equipo.a.aivencloud.com:28250/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_H8_FPnGMkLxxqv3ak7m}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hernandezluis5717@gmail.com
spring.mail.password=pwhsrxmkopqnohsy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
